apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: processing-service-mvc-tmpl
build:
  artifacts:
    - image: processing-service-mvc-tmpl
      context: .
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1

manifests:
  rawYaml:
    - target/classes/META-INF/dekorate/kubernetes.yml

