apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: microservice-template
requires:

test: []

build:
  artifacts:

    - image: gateway-react
      context: .
      buildpacks:
        builder: paketobuildpacks/builder:base
        env:
          - BP_MAVEN_PROJECT_MODULES=gateway-react
          - BP_MAVEN_BUILT_ARTIFACT=gateway-react/target/gateway-react-1.0-SNAPSHOT.jar



#kubectl port-forward pod/gateway-react-bc5b494b6-g4vr8 8080:80
#curl http://localhost:8080/api/processing/test
manifests:
  rawYaml:
    - gateway-react/target/classes/META-INF/dekorate/kubernetes.yml


#skaffold doesn't init this
deploy:
  kubeContext: kind-multi-node-cluster
