apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: microservice-template
requires:
#  - path: ./common-module/skaffold.yaml
#  - path: ./notification-service-mvc-tmpl/skaffold.yaml
#  - path: ./data-service-mvc-tmpl/skaffold.yaml
#  - path: ./processing-service-mvc-tmpl/skaffold.yaml
#  - path: ./eureka-server/skaffold.yaml
#  - path: ./gateway-react/skaffold.yaml

test: []

build:
  artifacts:
#    - image: processing-service-mvc-tmpl
#      context: .
#      buildpacks:
#        builder: paketobuildpacks/builder:base
#        env:
#          - BP_MAVEN_PROJECT_MODULES=processing-service-mvc-tmpl
#          - BP_MAVEN_BUILT_ARTIFACT=processing-service-mvc-tmpl/target/processing-service-mvc-tmpl-1.0-SNAPSHOT.jar

    - image: gateway-react
      context: .
      buildpacks:
        builder: paketobuildpacks/builder:base
        env:
          - BP_MAVEN_PROJECT_MODULES=gateway-react
          - BP_MAVEN_BUILT_ARTIFACT=gateway-react/target/gateway-react-1.0-SNAPSHOT.jar


#build:
#  artifacts:
#    - image: admin/data-service-mvc-tmpl
#      context: ./data-service-mvc-tmpl, .pom.xml
#      buildpacks:
#        builder: paketobuildpacks/builder:base
#    - image: admin/eureka-server
#      context: ./eureka-server, .pom.xml
#      buildpacks:
#        builder: paketobuildpacks/builder:base
#
#    - image: admin/gateway-react
#      context: ./gateway-react, .pom.xml
#      buildpacks:
#        builder: paketobuildpacks/builder:base
#    - image: admin/notification-service-mvc-tmpl
#      context: ./notification-service-mvc-tmpl
#      buildpacks:
#        builder: paketobuildpacks/builder:base

#    - image: admin/processing-service-mvc-tmpl
#      context: ./processing-service-mvc-tmpl
#      buildpacks:
#        builder: paketobuildpacks/builder:base


#profiles:
#  # Local cluster - we build and deploy things locally
#  - name: local
#    build:
#      local:
#        push: false
#    activation:
#      - kubeContext: kind

#kubectl port-forward pod/gateway-react-bc5b494b6-g4vr8 8080:80
#curl http://localhost:8080/api/processing/test
manifests:
  rawYaml:
    - gateway-react/target/classes/META-INF/dekorate/kubernetes.yml
#    - k8s/manifests/infrastructure/keycloak.yaml
#    - processing-service-mvc-tmpl/target/classes/META-INF/dekorate/kubernetes.yml
    - gateway-react/gateway-react-service.yaml
