apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: kafka-ui
  name: kafka-ui
  namespace: kafka-ns
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8080
  selector:
    io.kompose.service: kafka-ui
