apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092
              name: kafka-9092
            - containerPort: 29092
              name: kafka-29092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
      initContainers:
        - name: wait-for-zookeeper
          image: bitnami/bash
          command:
            - bash
            - -c
            - |
              echo "Waiting for Zookeeper to be ready..."
              until echo ruok | nc zookeeper 2181 | grep imok; do sleep 5; done
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka-9092
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: kafka-29092
      protocol: TCP
      port: 29092
      targetPort: 29092
  type: NodePort  # Exposes the service on each Node's IP at a static port