#postgres-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.2-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: keycloak
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              #              value: keycloak_password
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---

#postgres-pv.yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---


#postgres-pvc.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

#postgres-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
spec:
  selector:
    app: keycloak-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
#postgres-secrets.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  postgres-password: "keycloak_password"
---


#keycloak-deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.6
          args: ["start"]
          ports:
            - containerPort: 8484
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://keycloak-postgres:5432/keycloak
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres-password
            - name: KC_HOSTNAME
              value: localhost
            - name: KC_HTTP_PORT
              value: "8484"
            - name: KC_HOSTNAME_PORT
              value: "8484"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: admin-username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secrets
                  key: admin-password
---


#keycloak-secrets.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
stringData:
  admin-username: "admin"
  admin-password: "admin_password"

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: hbr-keycloak
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMVENDQWhXZ0F3SUJBZ0lVUVRQREtLUGtRYjZBYWNXN2htTFdtSThOOVg4d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pqRVJNQThHQTFVRUF3d0libWRwYm5oemRtTXhFVEFQQmdOVkJBb01DRzVuYVc1NGMzWmpNQjRYRFRJegpNRFF3T1RBM01qSTFOVm9YRFRJME1EUXdPREEzTWpJMU5Wb3dKakVSTUE4R0ExVUVBd3dJYm1kcGJuaHpkbU14CkVUQVBCZ05WQkFvTUNHNW5hVzU0YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0MKQVFFQWwrai9XcFVwQmtNdFBkemV4SGM0WlZHeENpdDlxUmRlV1FDay9JUXNVS1JkNGJSQTlFMXRGTzNheENnRQpKcGdYL1RHSHhid2VvMFVrU3BRU2czYzBoZ09KaWJKWGxlTmpsM0VTOXNmQWVCZEdVVFNMYzFtZ0x0Sm5sYklaClE2U3NnZ3RuZ3VGSFRZcFBoblBCZ1MzTkFjYk1WK01ZTlNEamVXQnJWTVI3RWM5YmJrT3d3VHNod1lXNEorTzUKdUdRTlhYUWNLWFdDdTRRZXpoUmNnOVhseEhWUTkxTURnNEJLbk5jUm9QdVRBaHdlWUJGSGZTenNJbTBQTzE5Qgp1c093cmJCTXNhV2UyZzRqbEIrZmtCMExLbS84RklRZnVXUS95eTVZYnpoK0kzT0xoUTdvYmNQUzlBNHl1R0Y1CnhVNExZbFRpNFN2UnBGSHN0QUxQT0JzVzd3SURBUUFCbzFNd1VUQWRCZ05WSFE0RUZnUVV5SkFxV21ISEtiTzEKWk0vMDhzc2NHRkFYQ1h3d0h3WURWUjBqQkJnd0ZvQVV5SkFxV21ISEtiTzFaTS8wOHNzY0dGQVhDWHd3RHdZRApWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQWE0Sk8xSGZ6Z0FPTTJUb3JmRFFEClhVNWM3bENjYmRDa1ZGeHBBQUlyeVo3WWljMm1mcllTNHMwMTU1dHVqUTNqLy9hVlYwTWFpOU96bGVTdmFockQKeU9veE9INzUrZWtUd1BkSHhvaHoxbFI5dW1yRUNBcXlIYnR2SXBCcFliTXFnZmp6KzJZNFBib290ZmhjMHVWZwptRFRsN1d3ak1XMURiQmlsM3ptSlRZZU5vSThUTXlCTWhwcGt0UndDVkM4VGRsRHNBUHZFWlZXUDBpL3VGOHBDCmZlZXFiaEtQSHZjZUV5V3Q4U0N0aDhmaDAycnViQlBjT3RycmtuUUlxakpxeVFPUFFXNjM1TGpxQTM0aWpBcEEKNDJxTlIzWGJvdTFOSkM3Wk8vdzJQYmtLZnlCNkNrdmRHQ3dOZWxjSnpRZXN1RWd6NDNrS240RUVIK09vUkFVTQprdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRQ1g2UDlhbFNrR1F5MDkKM043RWR6aGxVYkVLSzMycEYxNVpBS1Q4aEN4UXBGM2h0RUQwVFcwVTdkckVLQVFtbUJmOU1ZZkZ2QjZqUlNSSwpsQktEZHpTR0E0bUpzbGVWNDJPWGNSTDJ4OEI0RjBaUk5JdHpXYUF1MG1lVnNobERwS3lDQzJlQzRVZE5paytHCmM4R0JMYzBCeHN4WDR4ZzFJT041WUd0VXhIc1J6MXR1UTdEQk95SEJoYmduNDdtNFpBMWRkQndwZFlLN2hCN08KRkZ5RDFlWEVkVkQzVXdPRGdFcWMxeEdnKzVNQ0hCNWdFVWQ5TE93aWJRODdYMEc2dzdDdHNFeXhwWjdhRGlPVQpINStRSFFzcWIvd1VoQis1WkQvTExsaHZPSDRqYzR1RkR1aHR3OUwwRGpLNFlYbkZUZ3RpVk9MaEs5R2tVZXkwCkFzODRHeGJ2QWdNQkFBRUNnZ0VBT2dic2srTnFXbFFLMGhpdWw0bWE1MGovUVkwL1lQbm1Oa1ZDd0pxVWV2RnUKVXlzUnJNQnVySkgzQVByd0t2WHFJL05wazZTNlowK2YvMFQwbFhkUmZ1ZVhBQnc1eksyaGUxWGNFcHhXN3dpaworWndDc0x0SnJ0ajhiSGd0b21NaTZrSUU5aityaHZrUVM2R29CdnBCMXkzakhLZEl0ZktzTWM4YzhMSmsrSFlRCkltS09RWlpZQ3lzZlpQTld3NW5oR3k0VlpoeGo3T2J5MHJiLzU0bHVXNkdoSE9yY1hXRXVwbWY5UGNibVYzeHkKV0pvWmJOb1hKZjFEakhZeHltWmFIRnlPQ3ZVT1hDQmJiTzBQNENlbm0yYjJ0Wm8vWlo2VUxpeFNTUExiUlF3MApnbSs4K0prVzhRZS9WT2N5MjdNV0trbUVGUUV3T0dkQUR3dnQ3Q04rRVFLQmdRREhLd3JTVlpMa2FrZkFDTXZ3CkJCcXppT0xZQkxVRFhWNDVCV0w1eHpMK2lGbmJMUnROQndzeXd6MGh4KzNxeXdoRm5IQStKMURVcXg4cDkvR08KRER5Y0REZFUzbk1VandPNFNwMUdNeUtHb1B5bWk3aVFrWFBOT3Y3TXFpRmtvZitvcHBBSWV5U3RvTURvdkJidQpxL2lMWXM0MnJvNTF3NWtkYkVJTVE4TkpNd0tCZ1FERFFkTUg1V2NrNG96b3JlY3REU1VLZ1lUMzc4MnJHZzNFClRxTFdmYUZFcGtaUi9qVVU4OHp2VytBTTlDYXJQUFd1ZFZWaU1MNTAyWktqM0RCQ3pORGQ2ZkxCdHFmSGRCbnkKWnMvcWYvb2hya0kwOHIrRjZibFV0ejZJWWQxeFZBM2dENFJYY2tpWXpCWGhYYTNYVmVTNllBWFI4bmF4RmZiZwptYW9DUU5jVFZRS0JnUUNHWFRaV3dkNXdkSGJsU2NuenFZRXQvN294eTdNbWl2WEcrQ2hXcEJsMStCek9yWGFPCmw2THBZeWU1dzN4eGV2bWdwTEpnYS91dkRhYmZsR01FMXFLSkVBREFJN1oxZHlvbVNVZ2pGTnBGQXhTUGN4RlgKanBrV0txZTlBVVczODBaYnk4cTl2ZjMzbU15cjlrQnVVZHhDaEt6ajNRMUV5MmxmblNwTnhlVllXd0tCZ1FDSwplSXI5Ulk0QlZYMFNvZ21aSklKSlVoTUhkaFFJTEtEb3Y4K3hoMFN3RjY4MUJLK0dYV1BQdC90TGxIWTc2QzVmCmU2eUN4d2k2ZTNZSUtPWTg2VjJTa3cvcW11dWZnbEhJVzJ0RjVWNXhObENUbGplRzgzclFmbWVsZHFvQmJkZXQKTjdQbUJCRkI4ekh0TW05UGtBVjJ1eFJGa01ybHlTcmNtMzA2dmRzSlJRS0JnUUNINERRZEFNbnVMVk9UMVU4RwpzY0h2RmlpZFN2aEZ3dk45ejNpU2JmZytKbHRmYkxQbXlEREdGc2lIQzZQcG4yZHdneVp2MjZxYnRvVE9oZjRMClNkcTZDWjJVZi80c3RpbWJWbEtxK2J4UzdxMENIanYrYWtqUWwwbC9wY3cwOWdMU2ZDYmd5dEdMQXA4WW5VQXAKOWhiczF4RUFmcXJEdzdIbVkyb2dBanFuSFE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
---
#keycloak-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
---

#kubectl apply -f k8s/manifests/infrastructure/keycloak.yaml
#todo use in different namespace


