---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: 9dfd7cf2f7f6f34a83815dfc223fbec611873aa8
  labels:
    app.kubernetes.io/name: processing-service-mvc-tmpl
    app.kubernetes.io/part-of: default
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: processing-service-mvc-tmpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: processing-service-mvc-tmpl
      app.kubernetes.io/part-of: default
      app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: <<unknown>>
        app.dekorate.io/commit-id: 9dfd7cf2f7f6f34a83815dfc223fbec611873aa8
      labels:
        app.kubernetes.io/name: processing-service-mvc-tmpl
        app.kubernetes.io/part-of: default
        app.kubernetes.io/version: 1.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: default/processing-service-mvc-tmpl:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: processing-service-mvc-tmpl
          ports:
            - containerPort: 8082
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.dekorate.io/vcs-url: https://github.com/Pulladium/MicroServiceTemplate.git
    app.dekorate.io/commit-id: 9dfd7cf2f7f6f34a83815dfc223fbec611873aa8
  labels:
    app.kubernetes.io/name: processing-service-mvc-tmpl
    app.kubernetes.io/part-of: default
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: processing-service-mvc-tmpl
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8082
  selector:
    app.kubernetes.io/name: processing-service-mvc-tmpl
    app.kubernetes.io/part-of: default
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
