---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: 817887a1e8f4636b685f11a875911e4ffc08ce65
  labels:
    app.kubernetes.io/name: processing-service-mvc-tmpl
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: processing-service-mvc-tmpl
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0-SNAPSHOT
      app.kubernetes.io/name: processing-service-mvc-tmpl
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: <<unknown>>
        app.dekorate.io/commit-id: 817887a1e8f4636b685f11a875911e4ffc08ce65
      labels:
        app.kubernetes.io/version: 1.0-SNAPSHOT
        app.kubernetes.io/name: processing-service-mvc-tmpl
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: processing-service-mvc-tmpl:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: processing-service-mvc-tmpl
          ports:
            - containerPort: 8082
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: 817887a1e8f4636b685f11a875911e4ffc08ce65
  labels:
    app.kubernetes.io/name: processing-service-mvc-tmpl
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: processing-service-mvc-tmpl
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8082
  selector:
    app.kubernetes.io/name: processing-service-mvc-tmpl
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
