---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: cd839c824aa6128149dc99fadead8210e082949e
  labels:
    app.kubernetes.io/name: eureka-server
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eureka-server
      app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: <<unknown>>
        app.dekorate.io/commit-id: cd839c824aa6128149dc99fadead8210e082949e
      labels:
        app.kubernetes.io/name: eureka-server
        app.kubernetes.io/version: 1.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: Admin/eureka-server:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            successThreshold: 1
          name: eureka-server
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
